name: CI for flask app

on: 
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: check repositories
      uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-vbersion: '3.9'
    - name: install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: echo "build successfully"
